spring:
  profiles:
    include:
      - mail
      - file

  datasource:
    url: jdbc:mysql://localhost:3306/jspproject?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: always

server:
  port: 7777
  servlet:
    session:
      tracking-modes: cookie
    jsp:
      init-parameters:
        development: true

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG
      hibernate:
        resource:
          transaction: DEBUG